export const FoodAndDrinkTypes = {
  acai_shop: 'acai_shop',
  afghani_restaurant: 'afghani_restaurant',
  african_restaurant: 'african_restaurant',
  american_restaurant: 'american_restaurant',
  asian_restaurant: 'asian_restaurant',
  bagel_shop: 'bagel_shop',
  bakery: 'bakery',
  bar: 'bar',
  bar_and_grill: 'bar_and_grill',
  barbecue_restaurant: 'barbecue_restaurant',
  brazilian_restaurant: 'brazilian_restaurant',
  breakfast_restaurant: 'breakfast_restaurant',
  brunch_restaurant: 'brunch_restaurant',
  buffet_restaurant: 'buffet_restaurant',
  cafe: 'cafe',
  cafeteria: 'cafeteria',
  candy_store: 'candy_store',
  cat_cafe: 'cat_cafe',
  chinese_restaurant: 'chinese_restaurant',
  chocolate_factory: 'chocolate_factory',
  chocolate_shop: 'chocolate_shop',
  coffee_shop: 'coffee_shop',
  confectionery: 'confectionery',
  deli: 'deli',
  dessert_restaurant: 'dessert_restaurant',
  dessert_shop: 'dessert_shop',
  diner: 'diner',
  dog_cafe: 'dog_cafe',
  donut_shop: 'donut_shop',
  fast_food_restaurant: 'fast_food_restaurant',
  fine_dining_restaurant: 'fine_dining_restaurant',
  food_court: 'food_court',
  french_restaurant: 'french_restaurant',
  greek_restaurant: 'greek_restaurant',
  hamburger_restaurant: 'hamburger_restaurant',
  ice_cream_shop: 'ice_cream_shop',
  indian_restaurant: 'indian_restaurant',
  indonesian_restaurant: 'indonesian_restaurant',
  italian_restaurant: 'italian_restaurant',
  japanese_restaurant: 'japanese_restaurant',
  juice_shop: 'juice_shop',
  korean_restaurant: 'korean_restaurant',
  lebanese_restaurant: 'lebanese_restaurant',
  meal_delivery: 'meal_delivery',
  meal_takeaway: 'meal_takeaway',
  mediterranean_restaurant: 'mediterranean_restaurant',
  mexican_restaurant: 'mexican_restaurant',
  middle_eastern_restaurant: 'middle_eastern_restaurant',
  pizza_restaurant: 'pizza_restaurant',
  pub: 'pub',
  ramen_restaurant: 'ramen_restaurant',
  restaurant: 'restaurant',
  sandwich_shop: 'sandwich_shop',
  seafood_restaurant: 'seafood_restaurant',
  spanish_restaurant: 'spanish_restaurant',
  steak_house: 'steak_house',
  sushi_restaurant: 'sushi_restaurant',
  tea_house: 'tea_house',
  thai_restaurant: 'thai_restaurant',
  turkish_restaurant: 'turkish_restaurant',
  vegan_restaurant: 'vegan_restaurant',
  vegetarian_restaurant: 'vegetarian_restaurant',
  vietnamese_restaurant: 'vietnamese_restaurant',
  wine_bar: 'wine_bar',
};

// Helper function to validate establishment type
export function validateEstablishmentType(type) {
  if (!FoodAndDrinkTypes[type]) {
    const validTypes = Object.keys(FoodAndDrinkTypes).join(', ');
    throw new Error(
      `Invalid establishment type: ${type}. Valid types are: ${validTypes}`,
    );
  }
  return type;
}
