name: Frontend CI

on:
  push:
    branches: [main, develop, 'feature/*']
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/web/**'
      - 'packages/**'

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8'

jobs:
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm run lint

      - name: Run type checking
        run: pnpm run type-check

      - name: Run frontend tests
        run: pnpm run test:frontend
        env:
          CI: true

      - name: Build frontend
        run: pnpm run build:frontend
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: apps/web/.next
          retention-days: 1
